### ISSUE TITLE
commit compiling problem

### ISSUE THREAD

**Issue by The-Sapphire-Starship** [hiulit/cross-compile-godot-raspberry-pi#2]
For some reason it wont let me compile godot fro a commit(i have tried compiling a couple different commits), this is what it says when i try compiling a commits:

fatal: reference is not a tree: [commit/s]
ERROR: Something went wrong when checking out to '[commit/s]'.

[commit/s] = the commit is was trying to compile

**Comment by hiulit** [comment]
It seems like the commit you are trying to compile doesn't exist. It could be that you mispelled the commit hash or that your repo is not up to date. Have you tried updating the Godot repo? Try running `git pull` in the Godot source files folder.

I've just tried to compile `b169a16cb51b7203a171245acb5b4193c9d4bca4`(3.2.4 RC 5) and it compiled successfully.

```

**Comment by The-Sapphire-Starship** [comment]
Thanks, i didnt realize i needed a github repo of godot on my rpi in order to do this, that solved that problem but now im getting another error(im trying to compile 3.2.4 RC5):

----------
Godot source files directory: "/home/pi/godot/bin/cross-compile-godot-raspberry-pi/godot"
Godot toolchain directory: "/home/pi/godot/bin/cross-compile-godot-raspberry-pi/arm-godot-linux-gnueabihf_sdk-buildroot"
Godot compiled binaries directory: "/home/pi/godot/bin/cross-compile-godot-raspberry-pi/compiled-binaries"
Godot version/s to compile: ""
Godot commit/s to compile: "b169a16cb51b7203a171245acb5b4193c9d4bca4"
Binaries to compile: "editor"
Raspberry Pi version/s to compile: "4"
SCons jobs: "4"
Use LTO: "no"
Pack: "no"
----------

GODOT 'EDITOR' ('b169a16cb51b7203a171245acb5b4193c9d4bca4') FOR THE RASPBERRY PI '4'
------------------------------------------------------------------------------------
>> Cleaning SCons ...
./cross-compile-godot-raspberry-pi.sh: line 597: scons: command not found
ERROR: Something went wrong when cleaning generated files for the 'x11' platform.


Sorry for all these problems but im new github and still figuring things out

**Comment by hiulit** [comment]
I think you are trying to use this repo on a Pi and that won't work. This script is for cross-compiling Godot for the Pi **from a Linux x86_64 machine**.
If you want to compile Godot on a Pi, you can [use this guide](https://github.com/hiulit/Unofficial-Godot-Engine-Raspberry-Pi#compiling).

**Comment by The-Sapphire-Starship** [comment]
I was starting to wonder whether that was that was the issue, thanks for the help
