### ISSUE TITLE
Error: pathspec '3.3.2-stable' did not match any file(s) known to git

### ISSUE THREAD

**Issue by CMDR-Piboy314** [hiulit/cross-compile-godot-raspberry-pi#3]
### Error: pathspec '3.3.2-stable' did not match any file(s) known to git

I found this wonderful script while surfing the web 🏄 and decided to try it out! I spent a little time getting the options to exactly what I wanted. When I ran the command "`./cross-compile-godot-raspberry-pi.sh --toolchain-dir "./arm-godot-linux-sdk" --source-dir "./godot" --rpi-versions "4" --binaries "editor export-template" --scons-jobs "all" --godot-versions "3.3.2-stable" --use-lto`" I got an error.

`error: pathspec '3.3.2-stable' did not match any file(s) known to git
ERROR: Something went wrong when checking out to '3.3.2-stable'.`

I don't understand because I used `--get-tags` to find what I should use and this one was the most up-to-date.

Full Output:
```
'godot_toolchain_dir' set to './arm-godot-linux-sdk' in the config file.
'godot_source_files_dir' set to './godot' in the config file.
'raspberry_pi_versions' set to '4' in the config file.
'binaries' set to 'editor export-template' in the config file.
'scons_jobs' set to '2' in the config file.
'godot_versions' set to '3.3.2-stable' in the config file.
'use_lto' set to 'yes' in the config file.

Godot source files directory: "./godot"
Godot toolchain directory: "./arm-godot-linux-sdk"
Godot compiled binaries directory: "/home/MYUSERNAME/Godot/BuildRPI/cross-compile-godot-raspberry-pi/compiled-binaries"
Godot version/s to compile: "3.3.2-stable"
Godot commit/s to compile: ""
Binaries to compile: "editor export-template"
Raspberry Pi version/s to compile: "4"
SCons jobs: "2"
Use LTO: "yes"
Pack: "no"

error: pathspec '3.3.2-stable' did not match any file(s) known to git
ERROR: Something went wrong when checking out to '3.3.2-stable'.
```

I decided to try one of your examples in the README.md file (except I replaced the scons-jobs with all because I only have 2 cores on my x86 machine, `./cross-compile-godot-raspberry-pi.sh --godot-versions "3.2.3-stable" --rpi-versions "4" --binaries "editor" --scons-jobs "all"` because I thought that perhaps i made a mistake though this outputted the same error.

`
error: pathspec '3.2.3-stable' did not match any file(s) known to git
ERROR: Something went wrong when checking out to '3.2.3-stable'.
`

Please help,
&nbsp; &nbsp; &nbsp; &nbsp; CMDR-Piboy314

**Comment by hiulit** [comment]
HI there! I think that you have to `git pull` inside your godot's source code direcyory.
