### ISSUE TITLE
I have a small question

### ISSUE THREAD

**Issue by 2439905184** [hiulit/cross-compile-godot-raspberry-pi#5]
Does godot's offical toolchain have dev-libs for aarch64 linux?
![image](https://user-images.githubusercontent.com/29478722/181917321-0fe0b5a7-b81b-41f7-a8b7-6511e1265a16.png)
Because I notice you have a repo (it has some prebuilds godot)
And I tried your godot prebuild for raspberry-pi4-64bit .
This can be run at termux with linux (proot mode) on android.
So where did you get the aarch64 libs?
If I can get them. I think I will have my way to cross compile godot for aarch64 at x64 linux pc

**Comment by hiulit** [comment]
Hi there!
Not that I know of. Last time I checked, they didn't have a 64 bits toolchain.
I compile the 64 bits binaries on a Raspberry Pi 4 directly :P

**Comment by 2439905184** [comment]
Thanks for you answer me.
I think I shoud copy aarch64 libs form termux/linux

**Comment by hiulit** [comment]
If you ever got it working, please let me know so I can include it here. Thanks!
